name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.12.0
    - name: install packages
      run: sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev
    - run: zig build

  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.12.0
    - run: zig build
