name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  freebsd-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/freebsd-vm@v1
      with:
        copyback: false
        prepare: |
          pkg install -y webkit2-gtk3 wget
        run: |
          wget https://ziglang.org/download/0.12.1/zig-freebsd-x86_64-0.12.1.tar.xz
          tar -xvf zig-freebsd-x86_64-0.12.1.tar.xz
          ./zig-freebsd-x86_64-0.12.1/zig build

  netbsd-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/netbsd-vm@v1
      with:
        copyback: false
        prepare: |
          PKG_PATH="http://cdn.NetBSD.org/pub/pkgsrc/packages/NetBSD/$(uname -p)/$(uname -r|cut -f '1 2' -d.)/All/"
          export PKG_PATH
          /usr/sbin/pkg_add pkgin
          pkgin -y install webkit-gtk wget
          cat /var/db/pkgin/pkg_install-err.log # really did i use echo instead of cat !!!
        run: |
          wget http://cdn.netbsd.org/pub/pkgsrc/packages/NetBSD/x86_64/9.0_current/All/zig-0.12.0nb2.tgz
          tar -xvf zig-0.12.0nb2.tgz
          ./bin/zig build

  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.12.0
    - name: install packages
      run: sudo apt-get install libgtk-3-dev libwebkit2gtk-4.0-dev
    - run: zig build

  macos-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.12.0
    - run: zig build

  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: goto-bus-stop/setup-zig@v2
      with:
        version: 0.12.0
    - run: zig build
